name = "Diaspora"
version = "0.1.0"
defaultTargets = ["Diaspora"]

[[lean_lib]]
name = "Diaspora"

[[lean_exe]]
name = "diaspora"
root = "Main"

[[require]]
name = "mathlib"
scope = "leanprover-community"
